Parameters:

    EnvironmentName:
        Description: An Environment name that will be prefixed to resources
        Type: String

    VpcCIDR:
        Description: Please enter the IP range (CIDR notation) for the VpcCIDR
        Type: String
        Default: 10.0.0.0/16

    PublicSubnet1CIDR:
        Description: CidrBlock for PublicSubnet1
        Type: String
        Default: 10.0.1.0/24

    PublicSubnet2CIDR:
        Description: CidrBlock for PublicSubnet2
        Type: String
        Default: 10.0.2.0/24

    PrivateSubnet1CIDR:
        Description: CidrBlock for PrivateSubnet1
        Type: String
        Default: 10.0.3.0/24
    
    PrivateSubnet2CIDR:
        Description: CidrBlock for PublicSubnet2
        Type: String
        Default: 10.0.4.0/24

Resources:
    VPC:
            Type: AWS::EC2::VPC
            Properties: 
                CidrBlock:
                   Ref: VpcCIDR
                EnableDnsHostnames: true
                Tags: 
                    - Key: Name
                      Value:
                       Ref: EnvironmentName

    InternetGateway:
            Type: AWS::EC2::InternetGateway
            Properties: 
                Tags: 
                    - Key: Name
                      Value:
                       Ref: EnvironmentName

   
    InternetGatewayAttachment:
            Type: AWS::EC2::VPCGatewayAttachment
            Properties: 
                InternetGatewayId:
                 Ref: InternetGateway
                VpcId:
                 Ref: VPC


    PublicSubnet1:       
            Type: AWS::EC2::Subnet
            Properties: 
                AvailabilityZone: 
                    Fn::Select: 
                    - 0
                    - Fn::GetAZs: ""
                CidrBlock:
                 Ref: PublicSubnet1CIDR
                VpcId: 
                 Ref: VPC
                Tags: 
                    - Key: Name
                      Value: 
                       Ref: EnvironmentName
                    - Key: Subent 
                      Value: "PublicSubnet1"

    PublicSubnet2:       
            Type: AWS::EC2::Subnet
            Properties: 
                AvailabilityZone: 
                    Fn::Select: 
                    - 1
                    - Fn::GetAZs: ""
                CidrBlock:
                 Ref: PublicSubnet2CIDR
                VpcId: 
                 Ref: VPC
                Tags: 
                    - Key: Name
                      Value: 
                       Ref: EnvironmentName
                    - Key: Subent 
                      Value: "PublicSubnet2"
               
    PrivateSubnet1:       
            Type: AWS::EC2::Subnet
            Properties: 
                AvailabilityZone: 
                    Fn::Select: 
                    - 0
                    - Fn::GetAZs: ""
                CidrBlock:
                 Ref: PrivateSubnet1CIDR
                VpcId: 
                 Ref: VPC
                Tags: 
                    - Key: Name
                      Value: 
                       Ref: EnvironmentName
                    - Key: Subent 
                      Value: "PrivateSubnet1"

    PrivateSubnet2:       
            Type: AWS::EC2::Subnet
            Properties: 
                AvailabilityZone: 
                    Fn::Select: 
                    - 1
                    - Fn::GetAZs: ""
                CidrBlock:
                 Ref: PrivateSubnet2CIDR
                VpcId: 
                 Ref: VPC
                Tags: 
                    - Key: Name
                      Value: 
                       Ref: EnvironmentName
                    - Key: Subent 
                      Value: "PrivateSubnet2"
